[phases.setup]
nixPkgs = ["chromium", "firefox", "libnss3", "libatk1.0-0", "libatk-bridge2.0-0", "libcups2", "libdrm2", "libxkbcommon0", "libxcomposite1", "libxdamage1", "libxfixes3", "libxrandr2", "libgbm1", "libasound2"]

[phases.build]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt",
    "playwright install chromium --with-deps"
]

[start]
cmd = "python implementation/api_server.py"
